### ISSUE TITLE
Use $XDG_DATA_HOME or $XDG_CONFIG_HOME.

### ISSUE THREAD

**Issue by RobertZenz** [oliversandli/NewFormattedFile#1]
The [XDG Base Directory Speecifications](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is quite a useful resource. Ideally, your tool would honor a set `$XDG_DATA_HOME`/`$XDG_CONFIG_HOME` for its configuration location.

**Comment by oliversandli** [comment]
Yes, I looked into that, but for some reason those env variables don't exist on my system (macOS High Sierra). I don't have access to a Linux machine at the moment to see if those variables exist there.

**Comment by RobertZenz** [comment]
They *might* be set, seldomly, agreed, but should still be honored.

**Comment by oliversandli** [comment]
Right, I'll add support for XDG later today.

**Comment by oliversandli** [comment]
Added support for $XDG_DATA_HOME.
