### ISSUE TITLE
Use $XDG_TEMPLATES_DIR as additional source for templates.

### ISSUE THREAD

**Issue by RobertZenz** [oliversandli/NewFormattedFile#2]
In GNOME and similar environments (MATE, Unity, etc.) there is `$XDG_TEMPLATES_DIR` available which points at a template directory. Ideally your tool would also draw templates from there, if available.

I believe the `.conf` convention you're using would not fit with that, though, as the documents in there are expected to have the correct extension (or, at least, should).

**Comment by RobertZenz** [comment]
Overall I'd advice to drop the `.conf` extension, as that yields a much cleaner and easier to manage directory, like this:

    templates:
        python2-main.py
        python3-main.py
        generic-script.sh
        bash-script.sh

**Comment by RobertZenz** [comment]
Scratch that last comment about the file names, I missed that you're using a different approach.

**Comment by oliversandli** [comment]
Appreciate the input! I prefer to keep the config/data files for my programs in one place across all systems; having multiple possible locations for the config files could cause unnecessary confusion/convolution. One single config directory keeps things a lot cleaner. Is there a specific benefit to supporting `$XDG_TEMPLATES_DIR`, other than simply giving the user the option (which I am not against)?

**Comment by RobertZenz** [comment]
I'd only use it as *additional* source. As I said, on certain systems this might already be populated with templates, though, in a different structure.

I do not want to say that you have to support this or that it works better or some such, but I figured that you want to be at least aware that this exists. I always like when people show me stuff I hadn't seen so far in my hobby projects, and this seems like a very good way to learn about the directory structure of various different environments and how they handle similar use-cases.

**Comment by oliversandli** [comment]
Aha, yes, after more research into `XDG` I understand your suggestion. I’ll change `XDG_DATA_HOME` to `XDG_CONFIG_HOME`, using that for integration with the `XDG` system. 

And I really do appreciate your suggestions/insight! I never really considered supporting `XDG` before, and I now have a better knowledge of config systems. Thanks!
